#pragma once

namespace LauncherLocalization
{
namespace
{
struct ChineseEntry { const char* en; const char* zhHans; const char* zhHant; };
constexpr ChineseEntry CHINESE_ENTRIES[]={
 {"System","系统","系統"},
 {"Language","语言","語言"},
 {"Launcher","启动器","啟動器"},
 {"Settings","设置","設定"},
 {"Game settings","游戏设置","遊戲設定"},
 {"Library & storage","游戏库与存储","遊戲庫與儲存"},
 {"File manager","文件管理器","檔案管理員"},
 {"SMB network shares","SMB 网络共享","SMB 網路共享"},
 {"Download covers","下载封面","下載封面"},
 {"Cover settings","封面设置","封面設定"},
 {"Download from SteamGridDB","从 SteamGridDB 下载","從 SteamGridDB 下載"},
 {"Import cover from file","从文件导入封面","從檔案匯入封面"},
 {"Online artwork","在线图片","線上圖片"},
 {"Local image","本地图片","本機圖片"},
 {"Search SteamGridDB and replace this game's custom cover with selected online artwork.","在 SteamGridDB 搜索并用所选在线图片替换此游戏的自定义封面。","在 SteamGridDB 搜尋並以所選線上圖片取代此遊戲的自訂封面。"},
 {"Choose a PNG, JPEG, WebP or BMP image from SD, USB or SMB storage. It is validated and saved safely as PNG.","从 SD、USB 或 SMB 存储中选择 PNG、JPEG、WebP 或 BMP 图片。图片会经验证并安全保存为 PNG。","從 SD、USB 或 SMB 儲存中選擇 PNG、JPEG、WebP 或 BMP 圖片。圖片會經驗證並安全儲存為 PNG。"},
 {"Remove custom cover","移除自定义封面","移除自訂封面"},
 {"Select local cover","选择本地封面","選擇本機封面"},
 {"Cover imported","封面已导入","封面已匯入"},
 {"Custom cover removed","自定义封面已移除","自訂封面已移除"},
 {"Cover import failed","封面导入失败","封面匯入失敗"},
 {"Cover removal failed","封面移除失败","封面移除失敗"},
 {"Remove custom cover?","移除自定义封面？","移除自訂封面？"},
 {"The downloaded or imported cover will be deleted.","已下载或导入的封面将被删除。","已下載或匯入的封面將被刪除。"},
 {"The launcher will use the game's embedded artwork when available.","启动器将在可用时使用游戏内嵌的图片。","啟動器將在可用時使用遊戲內嵌的圖片。"},
 {"Importing local cover","正在导入本地封面","正在匯入本機封面"},
 {"Search","搜索","搜尋"},
 {"Favorites","收藏","收藏"},
 {"Collections","合集","合集"},
 {"All games","全部游戏","全部遊戲"},
 {"Reset","重置","重設"},
 {"Setting reset to default","设置已重置为默认值","設定已重設為預設值"},
 {"Check for Updates","检查更新","檢查更新"},
 {"SteamGridDB API key","SteamGridDB API 密钥","SteamGridDB API 金鑰"},
 {"Loading game library...","正在加载游戏库...","正在載入遊戲庫..."},
 {"The first page will appear as soon as it is ready.","第一页准备好后将立即显示。","第一頁準備好後將立即顯示。"},
 {"Return to the HOME Menu?","返回主页菜单？","返回主頁選單？"},
 {"Active scans and network operations will be cancelled safely.","正在进行的扫描和网络操作将安全取消。","正在進行的掃描和網路操作將安全取消。"},
 {"Finishing background operations safely.","正在安全完成后台操作。","正在安全完成背景操作。"},
 {"Install","安装","安裝"},
 {"Installing...","正在安装...","正在安裝..."},
 {"Applet mode installer","小程序模式安装器","小程式模式安裝器"},
 {"HOME Menu shortcut installed.","主页菜单快捷方式已安装。","主頁選單捷徑已安裝。"},
 {"Shortcut failed","快捷方式创建失败","捷徑建立失敗"},
 {"Unknown error","未知错误","未知錯誤"},
 {"Back","返回","返回"},
 {"Choose","选择","選擇"},
 {"Info","信息","資訊"},
 {"On","开","開"},
 {"Off","关","關"},
 {"Enabled","已启用","已啟用"},
 {"Disabled","已禁用","已停用"},
 {"Change","更改","變更"},
 {"Select","选择","選擇"},
 {"Open","打开","開啟"},
 {"Close","关闭","關閉"},
 {"Cancel","取消","取消"},
 {"Continue","继续","繼續"},
 {"Launch","启动","啟動"},
 {"Sort","排序","排序"},
 {"Game Menu","游戏菜单","遊戲選單"},
 {"Filter","筛选","篩選"},
 {"Page","页","頁"},
 {"Quit","退出","退出"},
 {"Graphics","图形","圖形"},
 {"Frame Generation","帧生成","幀生成"},
 {"Frame generation","帧生成","幀生成"},
 {"Frame generation performance","帧生成性能","幀生成效能"},
 {"Frame generation quality","帧生成质量","幀生成品質"},
 {"Performance display","性能显示","效能顯示"},
 {"Audio","音频","音訊"},
 {"Controller","手柄","手把"},
 {"Controller mapping","手柄映射","手把對應"},
 {"Hotkey binding","热键绑定","快捷鍵綁定"},
 {"Audio latency","音频延迟","音訊延遲"},
 {"Audio latency / stability","音频延迟 / 稳定性","音訊延遲 / 穩定性"},
 {"Theme","主题","主題"},
 {"Games per row","每行游戏数","每列遊戲數"},
 {"Rows per page","每页行数","每頁列數"},
 {"Show game titles","显示游戏标题","顯示遊戲標題"},
 {"Show region flags","显示地区标识","顯示地區標識"},
 {"Show custom settings badges","显示自定义设置标记","顯示自訂設定標記"},
 {"UI animations","界面动画","介面動畫"},
 {"Launcher appearance","启动器外观","啟動器外觀"},
 {"Launcher audio","启动器音频","啟動器音訊"},
 {"Launcher language","启动器语言","啟動器語言"},
 {"Launcher updates","启动器更新","啟動器更新"},
 {"Library layout","游戏库布局","遊戲庫版面"},
 {"Sound effects","音效","音效"},
 {"Check updates at boot","启动时检查更新","啟動時檢查更新"},
 {"Global setting","全局设置","全域設定"},
 {"Per-game setting","单游戏设置","單遊戲設定"},
 {"Exit Drastic DS?","退出 Drastic DS？","退出 Drastic DS？"},
 {"Closing Drastic DS...","正在关闭 Drastic DS...","正在關閉 Drastic DS..."},
 {"Drastic DS is running in applet mode.","Drastic DS 正在以小程序模式运行。","Drastic DS 正在以小程式模式執行。"},
 {"Install a HOME Menu shortcut to run it with full memory and normal performance.","安装主页菜单快捷方式以使用完整内存让模拟器在正常性能下运行。","安裝主頁選單捷徑以使用完整記憶體讓模擬器在正常效能下執行。"},
 {"Renderer","渲染器","渲染器"},
 {"Low-latency Vulkan","低延迟 Vulkan","低延遲 Vulkan"},
 {"Screen layout","屏幕布局","螢幕版面"},
 {"Custom layout editor...","自定义布局编辑器...","自訂版面編輯器..."},
 {"Lock native aspect ratio","锁定原生宽高比","鎖定原生寬高比"},
 {"Custom screen layout","自定义屏幕布局","自訂螢幕版面"},
 {"Top screen","上屏","上螢幕"},
 {"Touch screen","触摸屏","觸控螢幕"},
 {"Aspect lock: On","宽高比锁定：开","寬高比鎖定：開"},
 {"Aspect lock: Off","宽高比锁定：关","寬高比鎖定：關"},
 {"Native 4:3","原生 4:3","原生 4:3"},
 {"Native 3:4","原生 3:4","原生 3:4"},
 {"Current ratio","当前比例","目前比例"},
 {"Custom","自定义","自訂"},
 {"Swap DS screens","交换 DS 屏幕","交換 DS 螢幕"},
 {"Rotation","旋转","旋轉"},
 {"Screen gap","屏幕间距","螢幕間距"},
 {"Integer scaling","整数缩放","整數縮放"},
 {"Drastic filter","DraStic 滤镜","DraStic 濾鏡"},
 {"Custom shader...","自定义着色器...","自訂著色器..."},
 {"Show FPS","显示 FPS","顯示 FPS"},
 {"High-resolution 3D","高分辨率 3D","高解析度 3D"},
 {"Threaded 3D","多线程 3D","多執行緒 3D"},
 {"Disable edge marking","禁用边缘标记","停用邊緣標記"},
 {"16-bit color","16 位颜色","16 位元色彩"},
 {"Frame blending","帧混合","幀混合"},
 {"Fix main-engine screen","修复主引擎屏幕","修復主引擎螢幕"},
 {"LSFG 2x (Vulkan only)","LSFG 2x（仅 Vulkan）","LSFG 2x（僅 Vulkan）"},
 {"Sound","声音","聲音"},
 {"Volume","音量","音量"},
 {"Microphone","麦克风","麥克風"},
 {"Microphone source","麦克风来源","麥克風來源"},
 {"Microphone level","麦克风电平","麥克風電平"},
 {"Microphone hotkey","麦克风热键","麥克風快捷鍵"},
 {"CPU worker threads","CPU 工作线程","CPU 工作執行緒"},
 {"Preload ROM","预加载 ROM","預先載入 ROM"},
 {"Auto-trim ROM","自动裁剪 ROM","自動裁剪 ROM"},
 {"Ignore card size limit","忽略卡带大小限制","忽略卡帶大小限制"},
 {"Always sync RTC","始终同步 RTC","一律同步 RTC"},
 {"Custom clock","自定义时钟","自訂時鐘"},
 {"Custom date and time","自定义日期和时间","自訂日期和時間"},
 {"Autosave interval","自动保存间隔","自動儲存間隔"},
 {"Default state slot","默认即时存档槽","預設即時存檔槽"},
 {"Lua scripts","Lua 脚本","Lua 指令碼"},
 {"Slot-2 accessory","Slot-2 配件","Slot-2 配件"},
 {"Savestate backup data","即时存档备份数据","即時存檔備份資料"},
 {"Raw save-file format","原始存档文件格式","原始存檔檔案格式"},
 {"Rumble Pak vibration","震动包震动","震動包震動"},
 {"Slot-2 Rumble Pak","Slot-2 震动包","Slot-2 震動包"},
 {"Gyro & accelerometer","陀螺仪与加速度计","陀螺儀與加速度計"},
 {"Analog stick as D-Pad","模拟摇杆作为十字键","類比搖桿作為十字鍵"},
 {"Analog deadzone %","模拟死区 %","類比死區 %"},
 {"Virtual stylus","虚拟触控笔","虛擬觸控筆"},
 {"Stylus touch button","触控笔触摸按钮","觸控筆觸控按鈕"},
 {"Stick cursor speed","摇杆光标速度","搖桿游標速度"},
 {"Motion sensitivity","体感灵敏度","體感靈敏度"},
 {"Recenter motion stylus","重新居中体感触控笔","重新置中體感觸控筆"},
 {"USB mouse stylus","USB 鼠标触控笔","USB 滑鼠觸控筆"},
 {"Fast-forward mode","快进模式","快轉模式"},
 {"Fast-forward hotkey","快进热键","快轉快捷鍵"},
 {"In-game menu","游戏内菜单","遊戲內選單"},
 {"Swap screens hotkey","交换屏幕热键","交換螢幕快捷鍵"},
 {"Save state","保存即时存档","儲存即時存檔"},
 {"Load state","加载即时存档","載入即時存檔"},
 {"Next state slot","下一个存档槽","下一個存檔槽"},
 {"Previous state slot","上一个存档槽","上一個存檔槽"},
 {"Reset game","重置游戏","重設遊戲"},
 {"Quit to launcher","退出到启动器","退出至啟動器"},
 {"Auto-fire modifier","连发修饰键","連發修飾鍵"},
 {"Close/open lid","关闭/打开上盖","關閉/開啟上蓋"},
 {"DS A","DS A","DS A"},
 {"DS B","DS B","DS B"},
 {"DS X","DS X","DS X"},
 {"DS Y","DS Y","DS Y"},
 {"DS L","DS L","DS L"},
 {"DS R","DS R","DS R"},
 {"DS Start","DS Start","DS Start"},
 {"DS Select","DS Select","DS Select"},
 {"D-Pad Up","十字键上","十字鍵上"},
 {"D-Pad Down","十字键下","十字鍵下"},
 {"D-Pad Left","十字键左","十字鍵左"},
 {"D-Pad Right","十字键右","十字鍵右"},
 {"Frames to skip","跳过帧数","跳過幀數"},
 {"Frame-skip method","跳帧方法","跳幀方法"},
 {"Safe frame skipping","安全跳帧","安全跳幀"},
 {"Fast-forward speed","快进速度","快轉速度"},
 {"Auto-fire speed","连发速度","連發速度"},
 {"Nickname","昵称","暱稱"},
 {"Favorite color","喜欢的颜色","喜歡的顏色"},
 {"Birthday month","生日月份","生日月份"},
 {"Birthday day","生日日期","生日日期"},
 {"Launcher rotation","启动器旋转","啟動器旋轉"},
 {"3D / Compatibility","3D / 兼容性","3D / 相容性"},
 {"Emulation / System","模拟 / 系统","模擬 / 系統"},
 {"Frame Rate Control","帧率控制","幀率控制"},
 {"Gameplay / Features","游戏玩法 / 功能","遊戲玩法 / 功能"},
 {"Nintendo DS Firmware","任天堂 DS 固件","任天堂 DS 韌體"},
 {"Manage collections","管理合集","管理合集"},
 {"Filter library","筛选游戏库","篩選遊戲庫"},
 {"Favorite / collections","收藏 / 合集","收藏 / 合集"},
 {"Favorite","收藏","收藏"},
 {"Rename","重命名","重新命名"},
 {"Delete collection","删除合集","刪除合集"},
 {"Search...","搜索...","搜尋..."},
 {"Create HOME shortcut","创建主页快捷方式","建立主頁捷徑"},
 {"Clear game settings","清除游戏设置","清除遊戲設定"},
 {"Delete game","删除游戏","刪除遊戲"},
 {"Game folders","游戏文件夹","遊戲資料夾"},
 {"Not configured","未配置","未設定"},
 {"Configured","已配置","已設定"},
 {"Complete","完整","完整"},
 {"Missing","缺失","缺失"},
 {"Display backend","显示后端","顯示後端"},
 {"Latency / performance","延迟 / 性能","延遲 / 效能"},
 {"Image scaling","图像缩放","影像縮放"},
 {"Post-processing","后处理","後處理"},
 {"Visual enhancement","视觉增强","視覺增強"},
 {"Performance / compatibility","性能 / 兼容性","效能 / 相容性"},
 {"Compatibility / visual trade-off","兼容性 / 视觉权衡","相容性 / 視覺權衡"},
 {"Performance / visual trade-off","性能 / 视觉权衡","效能 / 視覺權衡"},
 {"Game-specific workaround","特定游戏变通方案","特定遊戲變通方案"},
 {"Nintendo DS microphone","任天堂 DS 麦克风","任天堂 DS 麥克風"},
 {"CPU performance","CPU 性能","CPU 效能"},
 {"Loading / memory","加载 / 内存","載入 / 記憶體"},
 {"Compatibility / memory","兼容性 / 内存","相容性 / 記憶體"},
 {"Nintendo DS clock","任天堂 DS 时钟","任天堂 DS 時鐘"},
 {"Save protection","存档保护","存檔保護"},
 {"Savestates","即时存档","即時存檔"},
 {"Gameplay feature","游戏功能","遊戲功能"},
 {"Nintendo DS accessory","任天堂 DS 配件","任天堂 DS 配件"},
 {"Save compatibility","存档兼容性","存檔相容性"},
 {"Save-file compatibility","存档文件兼容性","存檔檔案相容性"},
 {"Motion input","体感输入","體感輸入"},
 {"Controller input","手柄输入","手把輸入"},
 {"Touch input","触摸输入","觸控輸入"},
 {"Hotkey behavior","热键行为","快捷鍵行為"},
 {"Compatibility / performance","兼容性 / 性能","相容性 / 效能"},
 {"Speed control","速度控制","速度控制"},
 {"Firmware profile","固件配置","韌體設定檔"},
 {"Launcher orientation","启动器方向","啟動器方向"},
 {"Chooses the Switch presentation backend. Vulkan (NVK) is recommended for performance and is required by LSFG. OpenGL uses native NVC0, while Zink runs OpenGL on NVK for an additional compatibility path.","选择 Switch 的显示后端。推荐使用 Vulkan (NVK) 以获得更好性能，且 LSFG 需要它。OpenGL 使用原生 NVC0，而 Zink 在 NVK 上运行 OpenGL 以提供额外兼容路径。","選擇 Switch 的顯示後端。推薦使用 Vulkan (NVK) 以獲得更好效能，且 LSFG 需要它。OpenGL 使用原生 NVC0，而 Zink 在 NVK 上執行 OpenGL 以提供額外相容路徑。"},
 {"Reduces queued Vulkan presentation work so new controller input reaches the display sooner. It can reduce performance headroom, so it is disabled by default.","减少排队的 Vulkan 显示工作，使新的手柄输入更快到达屏幕。可能会降低性能余量，因此默认禁用。","減少排隊的 Vulkan 顯示工作，使新的手把輸入更快到達螢幕。可能會降低效能餘量，因此預設停用。"},
 {"Arranges the two Nintendo DS screens. Hybrid modes enlarge one screen, single-screen modes hide the other, and Custom uses positions saved by either layout editor.","安排两个任天堂 DS 屏幕。混合模式放大其中一个屏幕，单屏模式隐藏另一个，自定义则使用任一布局编辑器保存的位置。","安排兩個任天堂 DS 螢幕。混合模式放大其中一個螢幕，單螢幕模式隱藏另一個，自訂則使用任一版面編輯器儲存的位置。"},
 {"Opens a preview editor for global or per-game custom screen positions. Saving selects the Custom layout.","打开预览编辑器以调整全局或单游戏的自定义屏幕位置。保存后会选择自定义布局。","開啟預覽編輯器以調整全域或單遊戲的自訂螢幕位置。儲存後會選擇自訂版面。"},
 {"Keeps each Nintendo DS screen at its native 4:3 shape, or 3:4 when rotated, while resizing a custom layout.","调整自定义布局大小时，将每个任天堂 DS 屏幕保持为原生 4:3，旋转后则为 3:4。","調整自訂版面大小時，將每個任天堂 DS 螢幕保持為原生 4:3，旋轉後則為 3:4。"},
 {"Exchanges the displayed positions of the top and touch screens. Touch input continues to follow the emulated touch screen.","交换上屏和触摸屏的显示位置。触摸输入仍跟随模拟的触摸屏。","交換上螢幕和觸控螢幕的顯示位置。觸控輸入仍跟隨模擬的觸控螢幕。"},
 {"Rotates gameplay and the in-game interface for book or tate play. Menu navigation directions remain tied to the physical controller.","旋转游戏画面和游戏内界面，以便竖屏或书籍模式游玩。菜单导航方向仍与物理手柄绑定。","旋轉遊戲畫面和遊戲內介面，以便直式或書籍模式遊玩。選單導覽方向仍與實體手把綁定。"},
 {"Adds space between the two emulated screens before the layout is fitted to the display. Larger gaps leave less room for the game image.","在布局适配到显示屏之前，在两个模拟屏幕之间添加间距。间距越大，游戏图像可用空间越小。","在版面適配到顯示螢幕之前，在兩個模擬螢幕之間新增間距。間距越大，遊戲影像可用空間越小。"},
 {"Uses whole-number scaling for sharper, evenly sized pixels. Depending on the layout, this can leave unused borders and prevent the image from filling the display.","使用整数倍缩放以获得更锐利、均匀的像素。根据布局，可能会留下未使用的边框，并阻止图像填满屏幕。","使用整數倍縮放以獲得更銳利、均勻的像素。根據版面，可能會留下未使用的邊框，並阻止影像填滿螢幕。"},
 {"Applies a GPU scaling filter after DraStic renders the screens. Filters may sharpen, smooth, or stylize the image; Custom uses the shader selected below.","在 DraStic 渲染屏幕后应用 GPU 缩放滤镜。滤镜可锐化、平滑或风格化图像；自定义使用下方选择的着色器。","在 DraStic 渲染螢幕後套用 GPU 縮放濾鏡。濾鏡可銳化、平滑或風格化影像；自訂使用下方選擇的著色器。"},
 {"Selects a DraStic .dfx custom shader. Choosing one automatically changes DraStic filter to Custom. Vulkan shaders also need their compiled .dfx.nxvk pack.","选择 DraStic .dfx 自定义着色器。选择后会自动将 DraStic 滤镜改为自定义。Vulkan 着色器还需要其编译好的 .dfx.nxvk 包。","選擇 DraStic .dfx 自訂著色器。選擇後會自動將 DraStic 濾鏡改為自訂。Vulkan 著色器還需要其編譯好的 .dfx.nxvk 包。"},
 {"Shows DraStic's on-screen speed and frame-rate indicator while a game is running.","在游戏运行时显示 DraStic 的屏幕速度和帧率指示器。","在遊戲執行時顯示 DraStic 的螢幕速度和幀率指示器。"},
 {"Renders Nintendo DS 3D graphics at twice their normal resolution. This improves 3D clarity but substantially increases emulation work and does not upscale 2D layers.","以两倍正常分辨率渲染任天堂 DS 3D 图形。可提升 3D 清晰度，但大幅增加模拟负担，且不会放大 2D 图层。","以兩倍正常解析度渲染任天堂 DS 3D 圖形。可提升 3D 清晰度，但大幅增加模擬負擔，且不會放大 2D 圖層。"},
 {"Offloads 3D screen-update work to another CPU thread. It can improve performance, but DraStic warns that some games may show graphical glitches, swapped screens, or instability; disable it when troubleshooting.","将 3D 屏幕更新工作卸载到另一个 CPU 线程。可提升性能，但 DraStic 警告部分游戏可能出现图形故障、屏幕交换或不稳定；排查问题时请禁用。","將 3D 螢幕更新工作卸載到另一個 CPU 執行緒。可提升效能，但 DraStic 警告部分遊戲可能出現圖形故障、螢幕交換或不穩定；排查問題時請停用。"},
 {"Disables the Nintendo DS edge-marking effect used to draw outlines around some 3D polygons. This can avoid edge-related glitches, but removes an intended visual effect.","禁用任天堂 DS 用于在部分 3D 多边形周围绘制轮廓的边缘标记效果。可避免边缘相关故障，但会移除预期的视觉效果。","停用任天堂 DS 用於在部分 3D 多邊形周圍繪製輪廓的邊緣標記效果。可避免邊緣相關故障，但會移除預期的視覺效果。"},
 {"Uses a lower-precision 16-bit texture format. It may improve performance or reduce memory use, but lowers image quality and can introduce color banding.","使用精度较低的 16 位纹理格式。可能提升性能或降低内存使用，但会降低图像质量并可能产生色带。","使用精度較低的 16 位元紋理格式。可能提升效能或降低記憶體使用，但會降低影像品質並可能產生色帶。"},
 {"Blends consecutive emulated frames. This can reproduce effects that rely on rapid flicker, but may soften motion or create visible ghosting.","混合连续模拟帧。可重现依赖快速闪烁的效果，但可能使运动变柔和或产生可见残影。","混合連續模擬幀。可重現依賴快速閃爍的效果，但可能使運動變柔和或產生可見殘影。"},
 {"Forces the main 2D+3D display engine onto the emulated top screen instead of honoring a game's engine swaps. It helps some games such as the Sonic titles, but can put content on the wrong screen in others.","强制将主 2D+3D 显示引擎固定在模拟上屏，而不遵循游戏的引擎交换。对部分游戏（如索尼克系列）有帮助，但在其他游戏中可能把内容放到错误屏幕。","強制將主 2D+3D 顯示引擎固定在模擬上螢幕，而不遵循遊戲的引擎交換。對部分遊戲（如索尼克系列）有幫助，但在其他遊戲中可能把內容放到錯誤螢幕。"},
 {"Generates one intermediate frame for each real frame to target a smoother 2x presentation. It does not increase emulation speed and may add artifacts or latency. Vulkan only.","为每个真实帧生成一个中间帧，以实现更流畅的 2 倍呈现。不会提高模拟速度，可能增加伪影或延迟。仅支持 Vulkan。","為每個真實幀生成一個中間幀，以實現更流暢的 2 倍呈現。不會提高模擬速度，可能增加偽影或延遲。僅支援 Vulkan。"},
 {"Sets the resolution used for optical-flow analysis. Half can improve motion detail but costs more GPU time and memory; Quarter is recommended on Switch.","设置光流分析使用的分辨率。一半可改善运动细节，但会消耗更多 GPU 时间和内存；在 Switch 上推荐使用四分之一。","設定光流分析使用的解析度。一半可改善運動細節，但會消耗更多 GPU 時間和記憶體；在 Switch 上推薦使用四分之一。"},
 {"Uses LSFG's lighter performance-oriented processing path. Disable it only when you prefer image quality and have enough GPU headroom.","使用 LSFG 更轻量、以性能为导向的处理路径。仅在优先图像质量且有足够 GPU 余量时禁用。","使用 LSFG 更輕量、以效能為導向的處理路徑。僅在優先影像品質且有足夠 GPU 餘量時停用。"},
 {"Enables or mutes emulated Nintendo DS sound.","启用或静音模拟的任天堂 DS 声音。","啟用或靜音模擬的任天堂 DS 聲音。"},
 {"Sets the final Switch output volume without changing the emulated game's own mixer settings.","设置最终 Switch 输出音量，不改变模拟游戏自身的混音设置。","設定最終 Switch 輸出音量，不改變模擬遊戲自身的混音設定。"},
 {"Controls DraStic's audio buffering. Lower settings react sooner but are more likely to crackle or stutter; higher settings are safer when a game cannot maintain steady speed.","控制 DraStic 的音频缓冲。较低设置反应更快，但更容易出现爆音或卡顿；当游戏无法保持稳定速度时，较高设置更安全。","控制 DraStic 的音訊緩衝。較低設定反應更快，但更容易出現爆音或卡頓；當遊戲無法保持穩定速度時，較高設定更安全。"},
 {"Enables the emulated DS microphone input path. Its source can be simulated noise or a compatible microphone connected to the Switch.","启用模拟 DS 麦克风输入路径。来源可以是模拟噪声或连接到 Switch 的兼容麦克风。","啟用模擬 DS 麥克風輸入路徑。來源可以是模擬雜訊或連接到 Switch 的相容麥克風。"},
 {"Simulated noise uses the configured microphone hotkey for games that expect blowing. External microphone captures real audio from a CTIA headset microphone or compatible USB input; Bluetooth microphone input is not supported by Switch.","模拟噪声使用配置的麦克风热键，适用于需要吹气的游戏。外部麦克风从 CTIA 耳机麦克风或兼容 USB 输入捕获真实音频；Switch 不支持蓝牙麦克风输入。","模擬雜訊使用設定的麥克風快捷鍵，適用於需要吹氣的遊戲。外部麥克風從 CTIA 耳機麥克風或相容 USB 輸入擷取真實音訊；Switch 不支援藍牙麥克風輸入。"},
 {"Sets the microphone strength supplied to the game for both simulated and external input.","设置提供给游戏的麦克风强度（模拟和外部输入均适用）。","設定提供給遊戲的麥克風強度（模擬和外部輸入均適用）。"},
 {"Feeds simulated white noise while held. This binding is intentionally inactive when External microphone is selected, because DraStic then receives the captured waveform directly.","按住时输入模拟白噪声。选择外部麦克风时此绑定故意无效，因为此时 DraStic 直接接收捕获的波形。","按住時輸入模擬白雜訊。選擇外部麥克風時此綁定故意無效，因為此時 DraStic 直接接收擷取的波形。"},
 {"Sets the number of host worker threads DraStic may use. Switch applications have three usable CPU cores, so 3 is recommended; reduce it only for troubleshooting.","设置 DraStic 可使用的主机工作线程数。Switch 应用程序有三个可用 CPU 核心，因此推荐 3；仅在排查问题时减少。","設定 DraStic 可使用的主機工作執行緒數。Switch 應用程式有三個可用 CPU 核心，因此推薦 3；僅在排查問題時減少。"},
 {"Loads an uncompressed ROM into memory before play for fast, consistent access. Disabling it lowers memory use but can increase storage access during emulation.","在游戏前将未压缩 ROM 加载到内存，以获得快速、一致的访问。禁用可降低内存使用，但会在模拟期间增加存储访问。","在遊戲前將未壓縮 ROM 載入到記憶體，以獲得快速、一致的存取。停用可降低記憶體使用，但會在模擬期間增加儲存存取。"},
 {"Uses only the ROM length declared in its Nintendo DS header. This can reduce memory use for oversized dumps, but should stay off for patched or malformed ROMs unless needed.","仅使用任天堂 DS 头中声明的 ROM 长度。可减少过大转储的内存使用，但除非必要，否则对打补丁或格式错误的 ROM 应保持关闭。","僅使用任天堂 DS 標頭中宣告的 ROM 長度。可減少過大轉儲的記憶體使用，但除非必要，否則對打補丁或格式錯誤的 ROM 應保持關閉。"},
 {"Ignores the normal Nintendo DS cartridge-size limit. Enable it only when an oversized patched ROM refuses to load.","忽略正常的任天堂 DS 卡带大小限制。仅在过大的打补丁 ROM 拒绝加载时启用。","忽略正常的任天堂 DS 卡帶大小限制。僅在過大的打補丁 ROM 拒絕載入時啟用。"},
 {"Continuously synchronizes the Nintendo DS clock to the Switch clock. Enabling a custom clock turns this off so time follows emulation speed and savestates instead.","持续将任天堂 DS 时钟同步到 Switch 时钟。启用自定义时钟会关闭此选项，使时间跟随模拟速度和即时存档。","持續將任天堂 DS 時鐘同步到 Switch 時鐘。啟用自訂時鐘會關閉此選項，使時間跟隨模擬速度和即時存檔。"},
 {"Starts the game from the custom date and time below. From then on the clock follows emulation speed and savestates. It takes effect after restarting the game.","使用下方自定义日期和时间启动游戏。之后时钟跟随模拟速度和即时存档。重启游戏后生效。","使用下方自訂日期和時間啟動遊戲。之後時鐘跟隨模擬速度和即時存檔。重新啟動遊戲後生效。"},
 {"Sets the local date and time supplied to DraStic when the game starts. This is useful for time-based events in games such as Pokemon and Animal Crossing.","设置游戏启动时提供给 DraStic 的本地日期和时间。对宝可梦、动物森友会等有时间事件的游戏很有用。","設定遊戲啟動時提供給 DraStic 的本機日期和時間。對寶可夢、動物森友會等有時間事件的遊戲很有用。"},
 {"Controls how often DraStic commits automatic in-game save data while running. Shorter intervals reduce the amount of progress at risk after a crash, but write to storage more often.","控制 DraStic 在运行时提交自动游戏存档的频率。较短间隔可减少崩溃后可能丢失的进度，但会更频繁写入存储。","控制 DraStic 在執行時提交自動遊戲存檔的頻率。較短間隔可減少崩潰後可能遺失的進度，但會更頻繁寫入儲存。"},
 {"Selects the savestate slot used by the quick save and quick load hotkeys. Slots range from 0 to 9.","选择快速保存和快速加载热键使用的即时存档槽。槽位范围 0 至 9。","選擇快速儲存和快速載入快捷鍵使用的即時存檔槽。槽位範圍 0 至 9。"},
 {"Allows DraStic Lua scripts to run for supported games. Disable it if you do not use scripts or when troubleshooting script-related behavior.","允许 DraStic Lua 脚本在支持的游戏中运行。如果不使用脚本或排查脚本相关行为时请禁用。","允許 DraStic Lua 指令碼在支援的遊戲中執行。如果不使用指令碼或排查指令碼相關行為時請停用。"},
 {"Chooses the accessory emulated in the Nintendo DS Slot-2 port. GBA Cart loads matching .gba/.sav files for supported game bonuses; the other modes emulate SRAM, rumble, or motion accessories.","选择在任天堂 DS Slot-2 端口模拟的配件。GBA 卡带加载匹配的 .gba/.sav 文件以支持游戏奖励；其他模式模拟 SRAM、震动或体感配件。","選擇在任天堂 DS Slot-2 連接埠模擬的配件。GBA 卡帶載入匹配的 .gba/.sav 檔案以支援遊戲獎勵；其他模式模擬 SRAM、震動或體感配件。"},
 {"Stores a copy of the in-game save inside each savestate so both remain synchronized. DraStic recommends keeping this enabled because mismatched saves can cause corruption, especially in Pokemon games.","在每个即时存档中存储游戏内存档的副本，以保持同步。DraStic 建议保持启用，因为不匹配的存档可能导致损坏，尤其是在宝可梦游戏中。","在每個即時存檔中儲存遊戲內存檔的副本，以保持同步。DraStic 建議保持啟用，因為不匹配的存檔可能導致損壞，尤其是在寶可夢遊戲中。"},
 {"Writes in-game backup memory as a raw save file for easier interchange with other emulators and tools. Leave it off when you need DraStic's normal save format.","将游戏内备份内存写入为原始存档文件，便于与其他模拟器和工具交换。需要 DraStic 正常存档格式时请保持关闭。","將遊戲內備份記憶體寫入為原始存檔檔案，便於與其他模擬器和工具交換。需要 DraStic 正常存檔格式時請保持關閉。"},
 {"Forwards an emulated Slot-2 Rumble Pak effect to Switch controller vibration. It only has an effect when a game and the selected Slot-2 accessory use rumble.","将模拟的 Slot-2 震动包效果转发到 Switch 手柄震动。仅当游戏和所选 Slot-2 配件使用震动时才有效。","將模擬的 Slot-2 震動包效果轉發到 Switch 手把震動。僅當遊戲和所選 Slot-2 配件使用震動時才有效。"},
 {"Forwards Joy-Con gyro and accelerometer data to DraStic's motion input. It is mainly useful with a compatible Slot-2 motion accessory or motion-aware homebrew.","将 Joy-Con 陀螺仪和加速度计数据转发到 DraStic 的体感输入。主要用于兼容的 Slot-2 体感配件或支持体感的自制软件。","將 Joy-Con 陀螺儀和加速度計資料轉發到 DraStic 的體感輸入。主要用於相容的 Slot-2 體感配件或支援體感的自製軟體。"},
 {"Lets the left analog stick act as the Nintendo DS D-Pad in addition to the physical D-Pad.","让左模拟摇杆除物理十字键外也可作为任天堂 DS 十字键使用。","讓左類比搖桿除實體十字鍵外也可作為任天堂 DS 十字鍵使用。"},
 {"Sets how far the left stick must move before it presses a DS direction. Raise it to prevent drift; lower it for faster response.","设置左摇杆需移动多远才会触发 DS 方向。提高可防止漂移；降低可加快响应。","設定左搖桿需移動多遠才會觸發 DS 方向。提高可防止漂移；降低可加快回應。"},
 {"Off disables the controller cursor. Right stick moves a relative cursor, while Motion controls map the calibrated controller angle to an absolute point on the DS touch screen.","关闭禁用手柄光标。右摇杆移动相对光标，而体感控制将校准后的手柄角度映射到 DS 触摸屏上的绝对点。","關閉停用手把游標。右搖桿移動相對游標，而體感控制將校準後的手把角度對應到 DS 觸控螢幕上的絕對點。"},
 {"Chooses the controller button that presses the virtual stylus at its current stick or motion-controlled cursor position.","选择在当前摇杆或体感控制光标位置按下虚拟触控笔的手柄按钮。","選擇在目前搖桿或體感控制游標位置按下虛擬觸控筆的手把按鈕。"},
 {"Controls how quickly the right-stick stylus cursor moves across the DS touch screen.","控制右摇杆触控笔光标在 DS 触摸屏上的移动速度。","控制右搖桿觸控筆游標在 DS 觸控螢幕上的移動速度。"},
 {"Controls how far the motion stylus travels for a given controller tilt. Recenter after changing how you hold the Switch, Joy-Con, or Pro Controller.","控制给定手柄倾斜时体感触控笔移动的距离。更改握持 Switch、Joy-Con 或 Pro 手柄的方式后请重新居中。","控制給定手把傾斜時體感觸控筆移動的距離。變更握持 Switch、Joy-Con 或 Pro 手把的方式後請重新置中。"},
 {"Calibrates the current controller angle as the center of the DS touch screen. It is consumed by the wrapper while motion stylus mode is active.","将当前手柄角度校准为 DS 触摸屏的中心。在体感触控笔模式激活时由包装器使用。","將目前手把角度校準為 DS 觸控螢幕的中心。在體感觸控筆模式啟用時由包裝器使用。"},
 {"Lets a connected USB mouse point at the displayed DS touch screen. The left mouse button presses the stylus, and screen rotation is applied automatically.","允许连接的 USB 鼠标指向显示的 DS 触摸屏。鼠标左键按下触控笔，屏幕旋转自动应用。","允許連接的 USB 滑鼠指向顯示的 DS 觸控螢幕。滑鼠左鍵按下觸控筆，螢幕旋轉自動套用。"},
 {"Hold runs fast-forward only while its hotkey is held. Toggle keeps fast-forward active until the hotkey is pressed again.","按住仅在按住热键时运行快进。切换则保持快进直到再次按下热键。","按住僅在按住快捷鍵時執行快轉。切換則保持快轉直到再次按下快捷鍵。"},
 {"Sets how many frames the selected frame-skip method may omit. Zero disables skipping. Higher values can improve speed but make motion choppy and may visually break some games.","设置所选跳帧方法可省略的帧数。零禁用跳帧。较高值可提升速度，但会使运动卡顿，并可能在视觉上破坏部分游戏。","設定所選跳幀方法可省略的幀數。零停用跳幀。較高值可提升速度，但會使運動卡頓，並可能在視覺上破壞部分遊戲。"},
 {"Chooses when frames are omitted. Automatic skips when emulation falls behind; Fixed uses the configured ratio, while Aggressive and Maximum favor speed more strongly over smoothness and compatibility.","选择何时省略帧。自动在模拟落后时跳过；固定使用配置的比率，而激进和最大更优先速度而非流畅性和兼容性。","選擇何時省略幀。自動在模擬落後時跳過；固定使用設定的比率，而激進和最大更優先速度而非流暢性和相容性。"},
 {"Uses DraStic's more conservative frame-skipping behavior to reduce visual problems in sensitive games. It may provide less speedup than normal skipping.","使用 DraStic 更保守的跳帧行为，以减少敏感游戏中的视觉问题。可能比正常跳帧提供更少的加速。","使用 DraStic 更保守的跳幀行為，以減少敏感遊戲中的視覺問題。可能比正常跳幀提供更少的加速。"},
 {"Caps the speed used while fast-forward is active. 50% acts as slow motion; Unlimited runs only as fast as the Switch and current game allow.","限制快进激活时的速度。50% 作为慢动作；无限制仅以 Switch 和当前游戏允许的最快速度运行。","限制快轉啟用時的速度。50% 作為慢動作；無限制僅以 Switch 和目前遊戲允許的最快速度執行。"},
 {"Sets how rapidly supported DS buttons repeat while the auto-fire modifier hotkey is active.","设置连发修饰热键激活时支持的 DS 按钮重复速度。","設定連發修飾快捷鍵啟用時支援的 DS 按鈕重複速度。"},
 {"Sets the nickname stored in the emulated Nintendo DS firmware profile. Games may display this name.","设置存储在模拟任天堂 DS 固件配置中的昵称。游戏可能会显示此名称。","設定儲存在模擬任天堂 DS 韌體設定檔中的暱稱。遊戲可能會顯示此名稱。"},
 {"Sets the language reported by the emulated DS firmware. Auto follows the Switch system language and falls back to English when that language is not supported by Nintendo DS.","设置模拟 DS 固件报告的语言。自动跟随 Switch 系统语言，当任天堂 DS 不支持该语言时回退到英语。","設定模擬 DS 韌體報告的語言。自動跟隨 Switch 系統語言，當任天堂 DS 不支援該語言時回退到英語。"},
 {"Sets the favorite color stored in the emulated Nintendo DS user profile using the original 16-color Nintendo DS palette. Some games use it for personalization.","使用原始 16 色任天堂 DS 调色板设置存储在模拟用户配置中的喜欢颜色。部分游戏用它进行个性化。","使用原始 16 色任天堂 DS 調色盤設定儲存在模擬使用者設定檔中的喜歡顏色。部分遊戲用它進行個人化。"},
 {"Sets the birthday month stored in the emulated Nintendo DS user profile.","设置存储在模拟任天堂 DS 用户配置中的生日月份。","設定儲存在模擬任天堂 DS 使用者設定檔中的生日月份。"},
 {"Sets the birthday day stored in the emulated Nintendo DS user profile.","设置存储在模拟任天堂 DS 用户配置中的生日日期。","設定儲存在模擬任天堂 DS 使用者設定檔中的生日日期。"},
 {"Changes the launcher background and visual theme. It does not affect gameplay rendering.","更改启动器背景和视觉主题。不影响游戏画面渲染。","變更啟動器背景和視覺主題。不影響遊戲畫面渲染。"},
 {"Rotates the complete SDL launcher by 0, 90, 180, or 270 degrees. The 90 and 270 degree modes use the portrait layout. Touch follows the displayed interface, while D-Pad and stick navigation keep their normal physical directions.","将整个 SDL 启动器旋转 0、90、180 或 270 度。90 和 270 度模式使用竖屏布局。触摸跟随显示的界面，而十字键和摇杆导航保持正常物理方向。","將整個 SDL 啟動器旋轉 0、90、180 或 270 度。90 和 270 度模式使用直式版面。觸控跟隨顯示的介面，而十字鍵和搖桿導覽保持正常實體方向。"},
 {"Sets how many game covers are displayed across each library row. More columns make each cover smaller.","设置游戏库每行显示的游戏封面数量。列数越多，每个封面越小。","設定遊戲庫每列顯示的遊戲封面數量。欄數越多，每個封面越小。"},
 {"Sets how many rows of game covers are shown on each library page. More rows make each cover smaller.","设置游戏库每页显示的游戏封面行数。行数越多，每个封面越小。","設定遊戲庫每頁顯示的遊戲封面列數。列數越多，每個封面越小。"},
 {"Shows or hides game names below their covers in the library.","在游戏库中显示或隐藏封面下方的游戏名称。","在遊戲庫中顯示或隱藏封面下方的遊戲名稱。"},
 {"Shows or hides the region flag in the top-left corner of each game cover.","显示或隐藏每个游戏封面左上角的地区旗帜。","顯示或隱藏每個遊戲封面左上角的地區旗幟。"},
 {"Shows or hides the square badge on games that have per-game settings. The settings themselves are not changed.","显示或隐藏有单游戏设置的游戏上的方形标记。设置本身不会更改。","顯示或隱藏有單遊戲設定的遊戲上的方形標記。設定本身不會變更。"},
 {"Enables launcher transitions, moving highlights, and animated theme effects.","启用启动器过渡、移动高亮和动画主题效果。","啟用啟動器過渡、移動高亮和動畫主題效果。"},
 {"Enables navigation, confirmation, and back sound effects in the SDL launcher.","启用 SDL 启动器中的导航、确认和返回音效。","啟用 SDL 啟動器中的導覽、確認和返回音效。"},
 {"Checks GitHub for a newer DrasticDS_nx release when the launcher starts. The check is skipped for HOME Menu game shortcuts.","启动器启动时检查 GitHub 是否有更新的 DrasticDS_nx 版本。主页菜单游戏快捷方式会跳过检查。","啟動器啟動時檢查 GitHub 是否有更新的 DrasticDS_nx 版本。主頁選單遊戲捷徑會跳過檢查。"},
 {"Maps the Nintendo DS A button to a Switch controller button.","将任天堂 DS A 按钮映射到 Switch 手柄按钮。","將任天堂 DS A 按鈕對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS B button to a Switch controller button.","将任天堂 DS B 按钮映射到 Switch 手柄按钮。","將任天堂 DS B 按鈕對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS X button to a Switch controller button.","将任天堂 DS X 按钮映射到 Switch 手柄按钮。","將任天堂 DS X 按鈕對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS Y button to a Switch controller button.","将任天堂 DS Y 按钮映射到 Switch 手柄按钮。","將任天堂 DS Y 按鈕對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS L shoulder button to a Switch controller button.","将任天堂 DS L 肩键映射到 Switch 手柄按钮。","將任天堂 DS L 肩鍵對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS R shoulder button to a Switch controller button.","将任天堂 DS R 肩键映射到 Switch 手柄按钮。","將任天堂 DS R 肩鍵對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS Start button to a Switch controller button.","将任天堂 DS Start 按钮映射到 Switch 手柄按钮。","將任天堂 DS Start 按鈕對應到 Switch 手把按鈕。"},
 {"Maps the Nintendo DS Select button to a Switch controller button.","将任天堂 DS Select 按钮映射到 Switch 手柄按钮。","將任天堂 DS Select 按鈕對應到 Switch 手把按鈕。"},
 {"Maps Nintendo DS D-Pad Up to a Switch controller button.","将任天堂 DS 十字键上映射到 Switch 手柄按钮。","將任天堂 DS 十字鍵上對應到 Switch 手把按鈕。"},
 {"Maps Nintendo DS D-Pad Down to a Switch controller button.","将任天堂 DS 十字键下映射到 Switch 手柄按钮。","將任天堂 DS 十字鍵下對應到 Switch 手把按鈕。"},
 {"Maps Nintendo DS D-Pad Left to a Switch controller button.","将任天堂 DS 十字键左映射到 Switch 手柄按钮。","將任天堂 DS 十字鍵左對應到 Switch 手把按鈕。"},
 {"Maps Nintendo DS D-Pad Right to a Switch controller button.","将任天堂 DS 十字键右映射到 Switch 手柄按钮。","將任天堂 DS 十字鍵右對應到 Switch 手把按鈕。"},
 {"Opens DraStic's in-game menu with the selected Switch button combination.","使用所选 Switch 按钮组合打开 DraStic 游戏内菜单。","使用所選手把按鈕組合開啟 DraStic 遊戲內選單。"},
 {"Holds or toggles fast-forward using the behavior selected by Fast-forward mode.","按住或切换快进，行为由快进模式决定。","按住或切換快轉，行為由快轉模式決定。"},
 {"Swaps the Nintendo DS top and bottom screens during gameplay.","在游戏过程中交换任天堂 DS 上下屏。","在遊戲過程中交換任天堂 DS 上下螢幕。"},
 {"Uses the selected button combination as the auto-fire modifier.","使用所选按钮组合作为连发修饰键。","使用所選按鈕組合作為連發修飾鍵。"},
 {"Closes or opens the emulated Nintendo DS lid.","关闭或打开模拟的任天堂 DS 上盖。","關閉或開啟模擬的任天堂 DS 上蓋。"},
 {"Saves a state to the currently selected savestate slot.","将状态保存到当前选择的即时存档槽。","將狀態儲存到目前選擇的即時存檔槽。"},
 {"Loads a state from the currently selected savestate slot.","从当前选择的即时存档槽加载状态。","從目前選擇的即時存檔槽載入狀態。"},
 {"Selects the next savestate slot.","选择下一个即时存档槽。","選擇下一個即時存檔槽。"},
 {"Selects the previous savestate slot.","选择上一个即时存档槽。","選擇上一個即時存檔槽。"},
 {"Resets the running Nintendo DS game.","重置正在运行的任天堂 DS 游戏。","重設正在執行的任天堂 DS 遊戲。"},
 {"Stops emulation and returns to the DraStic launcher.","停止模拟并返回 DraStic 启动器。","停止模擬並返回 DraStic 啟動器。"},
 {"Chooses the language used by the SDL launcher. System follows the Switch console language.","选择 SDL 启动器使用的语言。系统跟随 Switch 主机语言。","選擇 SDL 啟動器使用的語言。系統跟隨 Switch 主機語言。"},
};
}
}
